// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feyxfxdtyglfhffasrxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZleXhmeGR0eWdsZmhmZmFzcnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDczNjksImV4cCI6MjA2NTk4MzM2OX0.P7by_EisYoVvLS4snse_7WvsJNndyr_LFzpyYLLHTgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);